//------------------------------------------------------------------------------
// <auto-generated>
//    Ten kod źródłowy został wygenerowany na podstawie szablonu.
//
//    Ręczne modyfikacje tego pliku mogą spowodować nieoczekiwane zachowanie aplikacji.
//    Ręczne modyfikacje tego pliku zostaną zastąpione w przypadku ponownego wygenerowania kodu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlbionDataManager
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class albiondataEntities : DbContext
    {
        public albiondataEntities()
            : base("name=albiondataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<gold_prices> gold_prices { get; set; }
        public DbSet<groups> groups { get; set; }
        public DbSet<items> items { get; set; }
        public DbSet<market_orders> market_orders { get; set; }
        public DbSet<market_stats> market_stats { get; set; }
        public DbSet<recipes> recipes { get; set; }
    }
}
