//------------------------------------------------------------------------------
// <auto-generated>
//    Ten kod źródłowy został wygenerowany na podstawie szablonu.
//
//    Ręczne modyfikacje tego pliku mogą spowodować nieoczekiwane zachowanie aplikacji.
//    Ręczne modyfikacje tego pliku zostaną zastąpione w przypadku ponownego wygenerowania kodu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlbionDataManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class groups
    {
        public groups()
        {
            this.items = new HashSet<items>();
            this.groups1 = new HashSet<groups>();
        }
    
        public long id { get; set; }
        public string name { get; set; }
        public Nullable<long> parent_group { get; set; }
    
        public virtual ICollection<items> items { get; set; }
        public virtual ICollection<groups> groups1 { get; set; }
        public virtual groups groups2 { get; set; }
    }
}
