//------------------------------------------------------------------------------
// <auto-generated>
//    Ten kod źródłowy został wygenerowany na podstawie szablonu.
//
//    Ręczne modyfikacje tego pliku mogą spowodować nieoczekiwane zachowanie aplikacji.
//    Ręczne modyfikacje tego pliku zostaną zastąpione w przypadku ponownego wygenerowania kodu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlbionDataManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class items
    {
        public items()
        {
            this.recipes = new HashSet<recipes>();
            this.recipes1 = new HashSet<recipes>();
        }
    
        public long id { get; set; }
        public string codename { get; set; }
        public string name { get; set; }
        public long group_id { get; set; }
        public long tier { get; set; }
        public Nullable<long> quality { get; set; }
        public Nullable<long> level { get; set; }
    
        public virtual groups groups { get; set; }
        public virtual ICollection<recipes> recipes { get; set; }
        public virtual ICollection<recipes> recipes1 { get; set; }
    }
}
