//------------------------------------------------------------------------------
// <auto-generated>
//    Ten kod źródłowy został wygenerowany na podstawie szablonu.
//
//    Ręczne modyfikacje tego pliku mogą spowodować nieoczekiwane zachowanie aplikacji.
//    Ręczne modyfikacje tego pliku zostaną zastąpione w przypadku ponownego wygenerowania kodu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlbionDataManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class market_stats
    {
        public long id { get; set; }
        public string item_id { get; set; }
        public int location { get; set; }
        public Nullable<int> price_min { get; set; }
        public Nullable<int> price_max { get; set; }
        public Nullable<decimal> price_avg { get; set; }
        public Nullable<System.DateTime> timestamp { get; set; }
    }
}
