//------------------------------------------------------------------------------
// <auto-generated>
//    Ten kod źródłowy został wygenerowany na podstawie szablonu.
//
//    Ręczne modyfikacje tego pliku mogą spowodować nieoczekiwane zachowanie aplikacji.
//    Ręczne modyfikacje tego pliku zostaną zastąpione w przypadku ponownego wygenerowania kodu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlbionDataManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class recipes
    {
        public long id { get; set; }
        public long item_id { get; set; }
        public long amount { get; set; }
        public long crafted_item_id { get; set; }
    
        public virtual items items { get; set; }
        public virtual items items1 { get; set; }
    }
}
